---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
    use: generic
  notify: os_reboot

- name: Modify /etc/hosts file
  template:
    src: hosts_redhat.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  notify: os_reboot
